#!/usr/bin/python
DICT_EXT_CONV = {
    "part": "Partial Download",
    "doc": "Document",    
    "xls": "Worksheet",
    "docx": " Microsoft Office Open XML Format Document",
    "xlsx": "Microsoft Office Open XML Format Spreadsheet",
    "pdf": "Portable Document Format",
    "jpg": "JPEG or JIFF Image",
    "jpeg": "JPEG or JIFF Image",
    "html": "Hypertext Markup Language",
    "png": "Portable (Public) Network Graphic",
    "gif": "Graphic Interchange Format",
    "js": "JavaScript Source Code",
    "c": "C Source Code",
    "cpp": "C++ Source Code",
    "css": "CSS Source Code",
    "json": "JSON Source Code",
    "php": "PHP Script",
    "py": "Python Script",
    "java": "Java Source Code",
    "jar": "Java Binary",
    "exe": "Microsoft Windows Binary",
    "deb": "Software Package",
    "ppt": "Presentation",
    "pptx": "Microsoft Office Open XML Format Presentation",
    "zip": "Compressed Archive File",
    "gz": "Compressed Archive File",
    "bz2": "UNIX Compressed File",
    "mkv": "Video Stream",
}
